# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{UCSCBin}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hiroyuki MISHIMA"]
  s.date = %q{2010-10-28}
  s.description = %q{Utilities for UCSC Bioinfomatics's Genome Browser
      ( http://g  enome.ucsc.edu ) including calculation of a BIN index
       from a genomic interval to speed-up SQL queries, and conversion
       between 1-based full-closed (for humans) and 0-based half-open 
       (for machienes) intervals}
  s.email = %q{missy@be.to}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/UCSCBin.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/misshie/UCSCBin}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Calculate BIN indexes on UCSC Bioinformatics's Genome Browser}
  s.test_files = [
    "spec/UCSCBin_Utils_spec.rb",
     "spec/spec_helper.rb",
     "spec/UCSCBin_BinRange_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

